apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: postgres-pod
  template:
    metadata:
      labels:
        app: postgres-pod
    spec:
      tolerations: 
      - key: "key1"
        value: "data-storage"
        operator: "Equal"
        effect: "NoSchedule"
      containers:
      - name: postgres-container
        image: postgres:16
        env:
        - name: POSTGRES_PASSWORD
          value: "mypassword"
        ports:
        - containerPort: 5432 