apiVersion: v1
entries:
  teemii:
  - apiVersion: v2
    appVersion: "1.0"
    created: "2026-01-18T22:13:40.1040538-06:00"
    description: Teemii application
    digest: 636fec2883260540522e09575a0f8df236eccfc43dff799bfedf2b44ea99a709
    name: teemii
    type: application
    urls:
    - https://Dereckt23.github.io/Road_to_DevOps/teemii-0.1.0.tgz
    version: 0.1.0
generated: "2026-01-18T22:13:40.1040538-06:00"
