backend:
  replicas: 1
  image: dokkaner/teemii-backend
  port: 3000
  socketPort: 1555
  pvc:
    name: teemii-data
    mountPath: /data

frontend:
  replicas: 1
  image: dokkaner/teemii-frontend
  port: 80
  nodeport: 30080

pvc:
  name: teemii-data
  size: 5Gi
